version: '2'
services:
 node:
  build: .
  ports:
   - "8000:8000"
  volumes:
   - .:/usr/src/app
  networks:
   - appnet
  links:
   - db:db
 db:
  image: mysql:5.7
  ports:
   - "3306:3306"
  environment:
   MYSQL_ROOT_PASSWORD: secret
   MYSQL_DATABASE: gitbot
   MYSQL_USER: gim
   MYSQL_PASSWORD: gin
  volumes:
   - dbdata:/var/lib/mysql
  networks:
   - appnet

networks:
 appnet:
  driver: "bridge"

volumes:
 dbdata:
  driver: "local"
